Routing
WildCodeSchool/2022-09-JS-Lille-project-2-g2-travel pull request #18
Opened 2022-11-16 10:23 UTC by cartige

2022-11-16 10:37 UTC, PriscilliaAmmeux submitted a review, later dismissed

2022-11-17 12:44 UTC, LoicBrassart requested changes
Plz remove useles imports in package.json

2022-11-17 12:44 UTC, LoicBrassart commented on frontend/package.json
> +    "localforage": "^1.10.0",
Wat?

2022-11-17 12:44 UTC, LoicBrassart commented on frontend/package.json
> +    "match-sorter": "^6.3.1",
What's this one ?

2022-11-17 12:44 UTC, LoicBrassart commented on frontend/package.json
> +    "sort-by": "^1.2.0",
And this ?

2022-11-17 13:46 UTC, PriscilliaAmmeux approved these changes

2022-11-17 14:11 UTC, LoicBrassart approved these changes
Much better, no more Evils

2022-11-17 14:27 UTC, merged