site web responsive
WildCodeSchool/2022-09-JS-Lille-project-2-g2-travel pull request #19
Opened 2022-11-22 14:00 UTC by PriscilliaAmmeux

2022-11-22 14:16 UTC, Azahires approved these changes, later dismissed

2022-11-22 14:28 UTC, LoicBrassart requested changes
**Almost** no Evil

2022-11-22 14:28 UTC, LoicBrassart commented on frontend/src/components/Location/Location.jsx
> +// import axios from "axios";
dead code

2022-11-22 14:54 UTC, CharlyJuteau approved these changes

2022-11-22 14:55 UTC, CharlyJuteau submitted a review, later dismissed

2022-11-22 15:34 UTC, LoicBrassart requested changes
Why, ô why ? é_è

2022-11-22 15:34 UTC, LoicBrassart commented on package.json
> +    "axios": "^1.1.3"
Nope !

2022-11-22 16:01 UTC, CharlyJuteau submitted a review, later dismissed

2022-11-22 17:17 UTC, LoicBrassart submitted a review, later dismissed
Better

2022-11-23 08:39 UTC, Azahires approved these changes
Saw no evil as said a great viking !

2022-11-23 09:00 UTC, LoicBrassart approved these changes
Saw no Evil

2022-11-23 09:31 UTC, merged