Making hearder
WildCodeSchool/2022-09-JS-Lille-project-2-g2-travel pull request #4
Opened 2022-10-28 13:32 UTC by PriscilliaAmmeux

2022-10-28 14:20 UTC, Azahires approved these changes, later dismissed

2022-10-29 00:04 UTC, LoicBrassart requested changes
Please fix the global package file

2022-10-29 00:04 UTC, LoicBrassart commented on package.json
> +  }
Remove this, it has nothing to do in this package.json (global)

2022-10-29 00:04 UTC, LoicBrassart commented on package.json
> +{
Note (nothing to do) : This file is 100% modified, that's quite unsettling... Encoding error, maybe ?

2022-11-02 15:21 UTC, Azahires approved these changes

2022-11-02 15:21 UTC, Azahires submitted a review, later dismissed

2022-11-02 15:21 UTC, CharlyJuteau submitted a review, later dismissed

2022-11-03 09:01 UTC, LoicBrassart approved these changes, later dismissed
Better ! :ok_hand:

2022-11-03 09:34 UTC, CharlyJuteau submitted a review, later dismissed

2022-11-03 10:44 UTC, LoicBrassart submitted a review, later dismissed
Saw no Evil

2022-11-03 11:22 UTC, CharlyJuteau approved these changes

2022-11-03 16:40 UTC, LoicBrassart approved these changes
Saw no Evil

2022-11-03 16:42 UTC, merged