Add card components
WildCodeSchool/2022-09-JS-Lille-project-2-g2-travel pull request #5
Opened 2022-10-28 13:50 UTC by alexis-Pouril

2022-10-28 14:38 UTC, Azahires approved these changes

2022-10-28 14:39 UTC, Azahires approved these changes, later dismissed

2022-10-29 00:07 UTC, LoicBrassart requested changes
Please move the prop-types dependancy to the frontend folder

2022-10-29 00:07 UTC, LoicBrassart commented on package.json
>    }
This... shouldn't work ? The package should be installed in the `frontend` package.json, not in the global one. I'm surprised, I didn't think it'd fetch the package one level higher

2022-11-02 15:37 UTC, CharlyJuteau approved these changes

2022-11-03 09:03 UTC, LoicBrassart approved these changes
Much better! :ok_hand:

2022-11-03 09:05 UTC, merged