Adding CTA
WildCodeSchool/2022-09-JS-Lille-project-2-g2-travel pull request #7
Opened 2022-10-28 15:38 UTC by Azahires

Search component + LocaliseMe button without connecting API.

2022-10-28 19:46 UTC, cartige approved these changes, later dismissed

2022-10-29 00:14 UTC, LoicBrassart requested changes
Almost there, please fix ;-)

2022-10-29 00:14 UTC, LoicBrassart commented on package.json
>    }
Not here ; in the `frontend` one !

2022-10-29 00:14 UTC, LoicBrassart commented
Also: NOPE !
You do you PRs towards dev, not main ! ⚠️

2022-11-02 15:24 UTC, CharlyJuteau submitted a review, later dismissed

2022-11-03 09:07 UTC, LoicBrassart commented
Conflicts + Missing SM review: I'll come back later, you seem occupied :p

2022-11-03 09:15 UTC, CharlyJuteau approved these changes

2022-11-03 10:51 UTC, LoicBrassart approved these changes
Saw no Evil

2022-11-03 11:12 UTC, merged